APP_BUNDLE_ID = "com.parrot.studio"
DEFAULT_TRANSCRIPTION_MODEL = "whisper-1"
DEFAULT_TRANSLATION_MODEL = "gpt-4o-2024-11-20"
DEFAULT_CHUNK_SECONDS = 300

AUDIO_SAMPLE_RATE = 16_000
PROVIDER_SAMPLE_RATE = 24_000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH_BYTES = 2
AUDIO_FRAME_MS = 20
AUDIO_FRAME_BYTES = int(AUDIO_SAMPLE_RATE * AUDIO_FRAME_MS / 1000) * AUDIO_SAMPLE_WIDTH_BYTES

SUBTITLE_LOCK_MS = 3_000
SUBTITLE_FADE_MS = 2_000
SUBTITLE_UPDATE_THROTTLE_MS = 300
SUBTITLE_LARGE_DIFF_RATIO = 0.30
MAX_SUBTITLE_LINES = 2
MAX_SUBTITLE_LINE_CHARS = 42
